<?php require_once "templates/header.phtml" ?>

<?php foreach($categoria as $item): ?>
    <div class ="form-container">
        <form action = "modificarCategoria/<?=$item->id_categoria?>" method="POST" class="my-4">
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <label>Modificar categoria</label>
                        <input name="categoria";  type="text" class="form-control" value="<?= $item->categoria?>">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label>Fragil:</label>
                <select name="fragil" id="">
                    <option value="1">true</option>
                    <option value="0">false</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary mt-2">Modificar</button>
        </form>
    </div>
<?php endforeach?>

<?php require_once "templates/footer.phtml" ?>
