
<div class ="form-container">
    <form action = "agregarCategoria" method="POST" class="my-4">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Categoria:</label>
                    <input name="categoria";  type="text" class="form-control">
                </div>
            </div>
        </div>

        <div class="form-group">
            <label>Fragil:</label>
            <select name="fragil" id="">
                <option value="1">true</option>
                <option value="0">false</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>
