
<?php require_once("templates/header.phtml") ?>

<?php if($esAdmin):?>
    <?php require_once("templates/formularioCategorias.phtml")?>
<?php endif ?>


<div class="container-listado">
<ul class = 'list-group'>
    <?php foreach($categorias as $categoria): ?>
            <li class ='list-group-item list-group-item-dark'><span class="item-principal"><?= $categoria->categoria ?></span>
                <div class="links-listado">
                    <a href="mostrarProductoXCategoria/<?=$categoria->id_categoria?>" class="btn btn-dark">Ver productos</a>
                    <?php if($esAdmin):?>
                        <a href="eliminarCategoria/<?=$categoria->id_categoria ?>" type='button' class='btn btn-danger ml-auto'>Borrar</a>
                        <a href="formModificarCategoria/<?=$categoria->id_categoria?>" class="btn btn-success">Modificar</a>
                    <?php endif ?>
                </div>
            </li>
    <?php endforeach?>
</ul>
</div>

<?php require_once("templates/footer.phtml") ?>