

<div class ="form-container">
    <form action = "agregarProducto" method="POST" class="my-4">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Categoria:</label>
                    <select name="id_categoria" id="">
                        <option value="1">Mate</option>
                        <option value="2">Bombilla</option>
                        <option value="3">Matera</option>
                        <option value="4">Termo</option>
                        <option value="5">Yerba</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label>Nombre:</label>
            <input type="text" name ="nombre">
        </div>

        <div class="form-group">
            <label>Material:</label>
            <input type="text" name ="material">
        </div>

        <div class="form-group">
            <label>Color:</label>
            <input type="text" name ="color">
        </div>

        <div class="form-group">
            <label>Precio:</label>
            <input type="number" name ="precio">
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>


