<?php require_once "templates/header.phtml" ?>

<?php foreach($producto as $item): ?>
    <div class ="form-container">
        <form action = "modificarProducto/<?=$item->id_producto?>" method="POST" class="my-4">
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <label>Categoria:</label>
                        <select name="id_categoria" id="">
                            <?php foreach ($categorias as $categoria):?>
                            <option value="<?=$categoria->id_categoria ?>"> <?= $categoria->categoria ?> </option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <label>Modificar nombre</label>
                        <input name="nombre"  type="text" class="form-control" value="<?= $item->nombre?>">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <label>Modificar material</label>
                        <input name="material"  type="text" class="form-control" value="<?= $item->material?>">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <label>Modificar color</label>
                        <input name="color"  type="text" class="form-control" value="<?= $item->color?>">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <label>Modificar precio</label>
                        <input name="precio"  type="number" class="form-control" value="<?= $item->precio?>">
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Modificar</button>
        </form>
    </div>
<?php endforeach?>

<?php require_once "templates/footer.phtml" ?>