
<div class ="form-container">
    <form action = "agregarCategoria" method="POST" class="my-4">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Categoria:</label>
                    <input name="categoria";  type="text" class="form-control">
                </div>
            </div>
        </div>

        <div class="form-group">
            <label>Fragil:</label>
            <input name="fragil" type="text" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>
