<?php require_once("templates/header.phtml")?>
<div class="home">
    <h1>Bienvenidos a Mate Datos</h1>
    <div class="presentacion">
        <p>Esta es una pagina para verdaderos amantes del mate. Aqui encontraras
            todo lo que necesitas para tener un set matero completo y de calidad.
            Ofrecemos lo mejor del mercado y a unos precios increibles.
            Esta pagina fue desarrollada por los estudiantes Iñaki Gopar y Benjamín Villar González,
            dos aficionados a la cultura del mate.
        </p>
    </div>
    
</div>

<?php require_once("templates/footer.phtml")?>